// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_HeFoh2u8dB_od166I9DwANDye-3610',
    appId: '1:997577047207:web:ef550603a2d3095acf2f82',
    messagingSenderId: '997577047207',
    projectId: 'mobil-cihazlar-vize',
    authDomain: 'mobil-cihazlar-vize.firebaseapp.com',
    storageBucket: 'mobil-cihazlar-vize.appspot.com',
    measurementId: 'G-GGYYTSH8JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI3yy6aFKE6BrDR0zzBaL7tB1CZ_axNX0',
    appId: '1:997577047207:android:19826f3e20ecd9e6cf2f82',
    messagingSenderId: '997577047207',
    projectId: 'mobil-cihazlar-vize',
    storageBucket: 'mobil-cihazlar-vize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLDrKbP5K0bCvS2XvD7G-DYoceyNVf-cw',
    appId: '1:997577047207:ios:9ab756944be26cc7cf2f82',
    messagingSenderId: '997577047207',
    projectId: 'mobil-cihazlar-vize',
    storageBucket: 'mobil-cihazlar-vize.appspot.com',
    iosBundleId: 'com.example.vizeProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLDrKbP5K0bCvS2XvD7G-DYoceyNVf-cw',
    appId: '1:997577047207:ios:1925343c28df890ccf2f82',
    messagingSenderId: '997577047207',
    projectId: 'mobil-cihazlar-vize',
    storageBucket: 'mobil-cihazlar-vize.appspot.com',
    iosBundleId: 'com.example.vizeProje.RunnerTests',
  );
}
